In [40]:
# Bibliotecas
import numpy as np
from numpy import dot
from numpy.linalg import norm
import matplotlib.pyplot as plt



In [41]:
def metodo_gradiente(A, b, x_0, erro):
    erro_atual = [1]
    iteracao = 0
    x = [x_0]
    max_iter = 200
    
    while True:
        r = b - dot(A, x[iteracao])
#         print('r: \n', r)
        alfa = dot(r.T, r)/dot(dot(r.T, A), r)
#         print('\nalfa: \n', alfa[0,0])
        x.append((x[iteracao] + (alfa[0,0]* r)))
#         print('\nnext_x: \n', x[iteracao])
        
        iteracao+=1
        erro_atual.append( (norm(x[iteracao] - x[iteracao-1] )/norm(x[iteracao])))
        
#         print('\nerro: \n', erro_atual)
        
        if erro_atual[iteracao] <= erro:
            break
        if iteracao >= max_iter:
            print('\nMáximo de Interação Atingido! ')
            break
    return x, erro_atual
        

# Teste 1

In [32]:
# Valores Iniciais

A = np.array([[1,4],[1,3]])
b = np.array([[5,4]]).T
x_0 = np.array([[0.8,0.8]]).T
erro = 1e-5

print('A: \n', A)
print()
print('b: \n', b)
print()
print('x_0: \n', x_0)
print()
print('erro: ', erro)

resultado , erro_x= metodo_gradiente(A, b, x_0, erro)

print('\n----------RESULTADOS------------\n')

print('numero de Iterações: ', len(resultado)-1)
print('X Final: ', resultado[-1].flatten())
print('Erro final: ', erro_x[-1])

print('\nX:')
for i, a in enumerate(resultado): print(f'{i} : {a.flatten()}' )
print('\nErros: \n', erro_x)



A: 
 [[1 4]
 [1 3]]

b: 
 [[5]
 [4]]

x_0: 
 [[0.8]
 [0.8]]

erro:  1e-05

----------RESULTADOS------------

numero de Iterações:  9
X Final:  [1.00000149 0.99999958]
Erro final:  8.633298137413144e-06

X:
0 : [0.8 0.8]
1 : [1.03699422 0.98959538]
2 : [1.01592807 1.01592807]
3 : [0.99705377 1.00082863]
4 : [0.99873148 0.99873148]
5 : [1.00023464 0.99993401]
6 : [1.00010103 1.00010103]
7 : [0.99998131 1.00000526]
8 : [0.99999195 0.99999195]
9 : [1.00000149 0.99999958]

Erros: 
 [1, 0.21173376262044005, 0.023471411724835137, 0.01710948954406858, 0.0019014569727157846, 0.0013610503777885176, 0.00015122529595254657, 0.00010840437604568831, 1.204494671896268e-05, 8.633298137413144e-06]


# Teste 2

In [57]:
import numpy as np
from scipy.sparse.linalg import gmres

# Defina sua matriz A e vetor b do sistema linear Ax = b
A = np.array([[-1, -1, 1,1], [1, -1, 1,1], [-1, 1, -1,1], [1,1,1,1]])
b = np.array([1, 1, 1, 5])

# Use o GMRES para resolver o sistema linear Ax = b
x, info = gmres(A, b)

if info == 0:
    print("Solução encontrada:", x)
else:
    print("GMRES não convergiu para uma solução.")

Solução encontrada: [-3.83207955e-16  2.00000000e+00  2.00000000e+00  1.00000000e+00]
